name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Build the Docker image
        run: docker build -t silent-auction .
      
      - name: Tag Docker image
        run: docker tag silent-auction:latest ${{ secrets.DOCKERHUB_USERNAME }}/silent-auction:latest
      
      - name: Push to Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/silent-auction:latest