name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Create .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env

      - name: Debug - Print .env contents
        run: |
          echo "Contents of .env file:"
          cat .env
      
      - name: Debug - Check if .env file exists
        run: |
          if [ -f ".env" ]; then
            echo ".env file exists"
          else
            echo ".env file does not exist"
          fi
      
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/silent-auction:latest

      - name: Delete Old docker container
        run: sudo docker rm -f silent-auction || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            -p 3001:3001 \
            --name silent-auction \
            --env-file .env \
            ${{ secrets.DOCKERHUB_USERNAME }}/silent-auction

      - name: Debug - Check container logs
        run: sudo docker logs silent-auction

      - name: Debug - Print container environment variables
        run: sudo docker exec silent-auction env

      - name: Debug - Check if application can access environment variables
        run: |
          sudo docker exec silent-auction node -e "console.log('MYSQL_HOST:', process.env.MYSQL_HOST)"
          sudo docker exec silent-auction node -e "console.log('NODE_ENV:', process.env.NODE_ENV)"